name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  checkout-latest-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: tsukinaha/tsukimi
          fetch-depth: 0 # 获取所有 tags

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            > [!IMPORTANT]
            > This release is for Windows ONLY.

            Full-Changelog: https://github.com/tsukinaha/tsukimi/releases/tag/v0.20.0
          files: |
            *.toml
          tag_name: v0.20.2
