name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  checkout-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload Github Assets
        run: |
          echo "${{secrets.DADA}}" > hello.txt
          cat hello.txt
