name: Test

on:
  workflow_dispatch:
  push: 
    branches: [main]

jobs:
  build-and-push:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      # matrix:
      #   include:
      #     - platform: arm64
      #       arch: arm64v8

    steps:
      - uses: actions/checkout@v4
       
      - run: |
          cd installer
          Invoke-WebRequest -Uri https://github.com/tsukinaha/tsukimi/releases/download/v0.13.0/tsukimi-x86_64-windows-gnu-gtk_416.7z -OutFile tsukimi-x86_64.7z -UseBasicParsing
          7z x tsukimi-x86_64.7z -otsukimi-x86_64-windows
          makensis /V4 ./tsukimi-installer.nsi
          
      - uses: actions/upload-artifact@v4
        with:
          name: tsukimi-x86_64-windows-installer
          path: |
            installer/*.exe