name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  checkout-latest-tag:
    runs-on: windows-2025

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        shell: powershell
        run: |
          which makensis.exe
          ls 'C:\Program Files\'
          ls 'C:\Program Files (x86)\'
